version: '3'

services:
  postgres:
    image: postgres:14
    container_name: greenlight-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: greenlight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
